# AppId 的值唯一标识此应用。
# 不要在其他应用的安装程序中使用相同的 AppId 值。
app_id: 0577724c-126c-4643-9757-d33760667f01
publisher: WenAnrong
publisher_url: https://github.com/WenAnrong/pass_clip
display_name: 秘荚
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: "D:\\HELLO-WORLD"
# 这里的路径是相对于项目根目录的路径； 图标格式必须是ico格式，不能是png或其它
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - zh